student_count = 11
puts "The students of Villains Academy"
puts "--------------------------------"
#list
puts "Dr. Hannibal Lecter"
puts "--"
puts "Darth Vader"
puts "--"
puts "Nurse Ratched"
puts "--"
puts "Michael Corleone"
puts "--"
puts "Alex DeLarge"
puts "--"
puts "The Wicked Witch of the West"
puts "--"
puts "Terminator"
puts "--"
puts "Freddy Krueger"
puts "--"
puts "The Joker"
puts "--"
puts "Joffrey Baratheon"
puts "--"
puts "Norman Bates"
puts "--"
#finish caption
puts "Overall, we have #{student_count} great students"